# 開発用

version: '3'
services:
  jupyter:
    container_name: botorch-sampler-experiment
    build:
      context: .
      dockerfile: ./Dockerfile
    image: botorch-sampler-experiment
    ports:
      - 7008:7008
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - .:/app
    restart: always
    working_dir: /app/notebook
    command: jupyter lab --ip=0.0.0.0 --port=7011 --allow-root --autoreload
